// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYzHH1IA1P3UexyrRRpziEOpbid_P7gz8',
    appId: '1:49678424253:web:6adaad333ee96bfdf2bfd4',
    messagingSenderId: '49678424253',
    projectId: 'quizappnew-d7886',
    authDomain: 'quizappnew-d7886.firebaseapp.com',
    storageBucket: 'quizappnew-d7886.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7L0OdT0zpO8GzISMOVzvytpBNGcGZ_LA',
    appId: '1:49678424253:android:deddec5eb5504a49f2bfd4',
    messagingSenderId: '49678424253',
    projectId: 'quizappnew-d7886',
    storageBucket: 'quizappnew-d7886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl46eObMhqCBKiIzbpmDvlIs_RkAq7WVQ',
    appId: '1:49678424253:ios:e25823ff8b645cb6f2bfd4',
    messagingSenderId: '49678424253',
    projectId: 'quizappnew-d7886',
    storageBucket: 'quizappnew-d7886.firebasestorage.app',
    iosBundleId: 'com.example.mainproject3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl46eObMhqCBKiIzbpmDvlIs_RkAq7WVQ',
    appId: '1:49678424253:ios:e25823ff8b645cb6f2bfd4',
    messagingSenderId: '49678424253',
    projectId: 'quizappnew-d7886',
    storageBucket: 'quizappnew-d7886.firebasestorage.app',
    iosBundleId: 'com.example.mainproject3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYzHH1IA1P3UexyrRRpziEOpbid_P7gz8',
    appId: '1:49678424253:web:ec7ca0463240ecc5f2bfd4',
    messagingSenderId: '49678424253',
    projectId: 'quizappnew-d7886',
    authDomain: 'quizappnew-d7886.firebaseapp.com',
    storageBucket: 'quizappnew-d7886.firebasestorage.app',
  );
}
